#!/usr/bin/env python

# chris 2016-03-13

import os
import os.path
import subprocess
import sys
from argparse import ArgumentParser
from datetime import datetime
from getpass import getpass

# Little wrapper object for GPG keys.
class Key(object):
  __slots__ = 'length','algo','id','createdstamp','grip','userid'

  def __init__(self,*a):
    for field,value in zip(self.__slots__,a):
      if value is None:
        raise ValueError('%s cannot be None' % field)
      setattr(self,field,value)

    if self.algo != 1:
      raise ValueError('unknown algorithm id %s' % self.algo)
    self.algo = 'RSA'

    if len(self.id) != 16:
      raise ValueError('invalid key id length %r' % self.id)

    if len(self.grip) != 40:
      raise ValueError('invalid key grip length %r' % self.grip)

  def shortid(self): return self.id[-8:]

# Cross-platform support for FreeBSD and OS X (Homebrew).  Add other
# platforms if needed.  Homebrew support is a little messy due to
# non-centralized libexec.  The name of the directory under
# `/usr/local/opt` also changes depending on the version/recipe.  Dumb.
def getlibexec(bin):
  def isexe(path):
    return os.path.isfile(path) and os.access(path,os.X_OK)
  if sys.platform.startswith('freebsd'):
    path = '/usr/local/libexec'
  elif sys.platform == 'darwin':
    base = '/usr/local/opt'
    for path in os.listdir(base):
      if any(path.startswith(x) for x in ('gnupg','gpg')):
        path = os.path.join(base,path,'libexec')
        break
  else:
    raise Exception('unsupported platform %s' % sys.platform)
  path = os.path.join(path,bin)
  if isexe(path): return path
  raise Exception('%r not found in path; tried %r' % (bin, path))

def ensureagent():
  subprocess.check_call(('gpg-connect-agent','--quiet','/bye'))

# Fetch primary secret keys.  The details of the GPG colon format are
# detailed in the `doc/DETAILS` file in their repository.  Note that
# this will pull in the first user ID only for a given key.
def getkeys():
  args = 'gpg','--list-secret-keys','--with-keygrip','--with-colons'
  keyfields = subprocess.check_output(args)
  keyfields = keyfields.strip().split('\n')
  keyfields = [x.split(':') for x in keyfields]

  getting = False
  length = None
  algo = None
  id = None
  createdstamp = None
  grip = None
  for fields in keyfields:
    if not getting:
      if fields[0] == 'sec':
        getting = True
        length = int(fields[2])
        algo = int(fields[3])
        id = fields[4]
        createdstamp = datetime.fromtimestamp(int(fields[5]))
      continue
    if grip is None:
      if fields[0] != 'grp': raise Exception(fields)
      grip = fields[9]
      continue
    if fields[0] != 'uid': raise Exception(fields)
    userid = fields[9]

    yield Key(length,algo,id,createdstamp,grip,userid)

    grip = None
    createstamp = None
    id = None
    algo = None
    length = None
    getting = False

# This is based off of the prompt in GPG version 2.1.11.
template = '''Please enter the passphrase to unlock the OpenPGP secret key:
"%(userid)s"
%(length)s-bit %(algo)s key, ID %(id)s,
created %(createdstamp)s.

Passphrase: '''
def prompt(key):
  userid = key.userid
  length = key.length
  algo = key.algo
  id = key.shortid()
  createdstamp = key.createdstamp.strftime('%Y-%m-%d')
  return getpass(template % locals())

def preset(key,passphrase):
  args = getlibexec('gpg-preset-passphrase'),'--preset',key.grip
  p = subprocess.Popen(args,stdin=subprocess.PIPE)
  p.communicate(passphrase)
  if p.returncode:
    raise subprocess.CalledProcessError(p.returncode,args)

def main():
  # Argument parser just for a useful help message.
  descr = ("Start the GPG agent if it's not already running by quietly running "
  '`gpg-connect-agent /bye`. Fetch primary secret keys and prompt for their '
  'passphrases. Preset the passphrases with the GPG agent.')
  ArgumentParser(description=descr).parse_args()

  ensureagent()
  for key in getkeys():
    try: passphrase = prompt(key)
    except EOFError: return 3
    preset(key,passphrase)

try: sys.exit(main() or 0)
except KeyboardInterrupt: sys.exit(130)
